[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "python -m venv .venv",
  ".venv/bin/pip install --upgrade pip",
  ".venv/bin/pip install -r requirements.txt"
]

[phases.start]
cmd = ".venv/bin/python main.py"

[provider]
name = "python"
